import Config

if File.exists?(".env") do
  File.stream!(".env")
  |> Stream.map(&String.trim/1)
  |> Stream.reject(&(String.starts_with?(&1, "#") or &1 == ""))
  |> Stream.map(&String.split(&1, "=", parts: 2))
  |> Enum.each(fn
    [key, value] ->
      # Remove "export " prefix if present
      key = String.replace(key, "export ", "")
      # Remove quotes if present
      value = String.trim(value, "\"")
      System.put_env(key, value)

    _ ->
      :ok
  end)
end

# Configure your database
config :roomly, Roomly.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "roomly_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.

# Base endpoint config (always present)
base_endpoint_config = [
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "lM3LxEkTglXHnSi0t90AWkB54/D5cQf/pfGDDaGaXvPR6+HexWK7TAhLQrNPkMda",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:roomly, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:roomly, ~w(--watch)]}
  ]
]

# Add HTTPS config only if all required env vars are set
https_endpoint_config =
  case {System.get_env("CERT_KEYFILE"), System.get_env("CERT_CERTFILE"),
        System.get_env("LOCALHOST")} do
    {keyfile, certfile, host}
    when not is_nil(keyfile) and not is_nil(certfile) and not is_nil(host) ->
      [
        https: [
          port: 4001,
          keyfile: keyfile,
          certfile: certfile
        ],
        url: [
          host: host,
          port: 4001,
          scheme: "https"
        ]
      ]

    _ ->
      IO.puts(
        "⚠️  HTTPS disabled: missing CERT_CERTFILE, CERT_KEYFILE, or LOCALHOST environment variables"
      )

      []
  end

# Merge and apply endpoint config
config :roomly, RoomlyWeb.Endpoint, base_endpoint_config ++ https_endpoint_config

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :roomly, RoomlyWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/roomly_web/router\.ex$"E,
      ~r"lib/roomly_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :roomly, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
